module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      transitionProperty: { colors: "color, background-color, border-color, text-decoration-color, fill, stroke" },
      animation: {
        aurora1: "aurora1 18s ease-in-out infinite",
        aurora2: "aurora2 22s ease-in-out infinite",
        aurora3: "aurora3 26s ease-in-out infinite",
        fadeIn: "fadeIn 200ms ease-out",
        fadeUp: "fadeUp 200ms ease-out",
        toastIn: "toastIn 250ms cubic-bezier(.16,1,.3,1)",
        riseIn: "riseIn 320ms cubic-bezier(.16,1,.3,1) both",
      },
      keyframes: {
        aurora1: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(60px,40px) scale(1.08)" }, "66%": { transform: "translate(-30px,80px) scale(0.96)" } },
        aurora2: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(-50px,60px) scale(1.05)" }, "66%": { transform: "translate(40px,-30px) scale(1.1)" } },
        aurora3: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "50%": { transform: "translate(80px,-50px) scale(1.12)" } },
        fadeIn: { from: { opacity: "0", transform: "translateY(-4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        fadeUp: { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        toastIn: { from: { opacity: "0", transform: "translateY(10px) scale(.96)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
        riseIn: { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
    },
  },
  safelist: [
    { pattern: /^bg-(white|zinc|emerald|amber|red|fuchsia|sky|indigo)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^dark:bg-(zinc|emerald|amber|red|fuchsia|sky|indigo)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^dark:bg-(zinc|emerald|amber|red|fuchsia|sky|indigo)-[a-z0-9]*$/ },
    { pattern: /^dark:text-(zinc|emerald|red|fuchsia|sky)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^dark:text-(zinc|emerald|red|fuchsia|sky)-[a-z0-9]*$/ },
    { pattern: /^dark:border-(zinc|emerald)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^dark:border-(zinc|emerald)-[a-z0-9]*$/ },
    { pattern: /^dark:hover:bg-(zinc|emerald)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^dark:hover:text-(zinc|emerald)-[a-z0-9]*$/ },
    { pattern: /^dark:hover:border-emerald-500$/ },
    { pattern: /^bg-(white|zinc)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^text-(zinc|emerald|red)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^shadow-(emerald|indigo)-500\/30$/ },
    { pattern: /^border-(white|zinc)-[a-z0-9]*\/[0-9]+$/ },
    { pattern: /^mr-72$/ },
  ],
  plugins: [],
};
